name: deploy-client

on:
  push:
    paths:
      - "client/**"
  pull_request:
    paths:
      - "client/**"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12' ]
    name: Node ${{ matrix.node }}
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v2

      - name: Setup node with cache
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build client
        run: npm run build
        env:
          NEXT_PUBLIC_SERVER_URL: ${{ secrets.NEXT_PUBLIC_SERVER_URL }}
          NEXT_PUBLIC_SITE_DOMAIN: ${{ secrets.NEXT_PUBLIC_SITE_DOMAIN }}

      - name: Run tests
        run: npm run test:ci
      
      - name: Run linter
        run: npm run lint && npm run lint:cypress

      - name: Cypress run
        uses: cypress-io/github-action@v2
        env:
          CYPRESS_NEXT_PUBLIC_SERVER_URL: ${{ secrets.NEXT_PUBLIC_SERVER_URL }}
          CYPRESS_NEXT_PUBLIC_SITE_DOMAIN: ${{ secrets.NEXT_PUBLIC_SITE_DOMAIN }}
        with:
          working-directory: client
          start: npm start
  


