name: deploy-server

on:
  push:
    paths:
      - "server/**"
  pull_request:
    paths:
      - "server/**"
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12' ]
    name: Node ${{ matrix.node }}
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v2

      - name: Setup node with cache
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
          cache-dependency-path: server/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:ci
        env:
          IN_MEMORY_DATABASE: ${{ secrets.IN_MEMORY_DATABASE }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
      
